--[[

░▒▓████████▓▒░▒▓████████▓▒░░▒▓██████▓▒░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░▒▓███████▓▒░  
░▒▓█▓▒░      ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░      ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓██████▓▒░ ░▒▓██████▓▒░ ░▒▓████████▓▒░ ░▒▓█▓▒░   ░▒▓████████▓▒░▒▓██████▓▒░ ░▒▓███████▓▒░  
░▒▓█▓▒░      ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░      ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░      ░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░ 

]]

-- ========================================================
-- This configuration file is autogenerated by feather.
-- ========================================================

-- ========================================================
-- The global `feather` table exposes the configuration API.
-- ========================================================
--
-- Methods:
--
-- feather.config(tbl)
--   - Applies configuration.
--   - Can be called multiple times (or once).
--   - Config is merged into existing state:
--       - New keys are added.
--       - Existing keys are replaced by provided values.
--
-- Basic syntax:
--
--   feather.config({
--       input = { ... },
--       layout = { ... }
--   })
--
-- Can also be split into multiple calls:
--
--   feather.config({ input = { ... } })
--   feather.config({ layout = { ... } })
--
-- feather.monitor(tbl)
--   - Configures a monitor.
--   - Can be called multiple times to configure multiple monitors.
--   - Each monitor is configured by name.
--
-- feather.startup_exec(string)
--   - Executes a program on startup.
-- ========================================================

-- configure monitors using feather.monitor() like this:

feather.monitor({
    name = "HDMI-A-1",
    mode = "1920x1080@120", -- the syntax is WIDTHxHEIGHT@REFRESH, e.g. "1920x1080@120"
})

-- use feather.startup_exec() to execute programs on startup like this:

feather.startup_exec("kitty")

feather.config({
    -- ========================================================
    -- Input configuration
    -- ========================================================

    input = {
        -- Keyboard configuration

        keyboard = {
            -- XKB keyboard layout (e.g., "us", "de", "fr").
            -- Default: "us"

            layout = "us",

            -- Key repeat rate in characters per second.
            -- Default: 25

            repeat_rate = 25,

            -- Delay before key repeat starts in milliseconds.
            -- Default: 600

            repeat_delay = 600
        }
    }
})

feather.config({
    -- ========================================================
    -- Layout configuration
    -- ========================================================

    layout = {
        -- Available options: master

        layout = "master",

        -- Master layout configuration
        -- Controls behavior of the master/stack tiling layout.

        master = {
            -- Master window size factor.
            -- Default: 0.5 = 50% of screen for the master window.
            -- Lower values shrink the master window, higher values enlarge it.

            mFact = 0.5
        }
    }
})