-- Generated by Feather

-- All of these below are valid syntax.

-- feather.input.keyboard({
--     layout = "us"
-- })

-- feather.input.keyboard.layout = "us"

-- feather.input({
--     keyboard = {
--         layout = "us"
--     }
-- })

-- --------------------------------------------------------
-- Monitor
-- --------------------------------------------------------

-- feather.monitor({
   -- name = "HDMI-A-1",
   -- mode = "1920x1080@120",
-- })

-- --------------------------------------------------------
-- Startup
-- --------------------------------------------------------

for i = 1, 2 do
    feather.exec("kitty")
end

-- --------------------------------------------------------
-- Input
-- --------------------------------------------------------

feather.input.keyboard({
    -- XKB keyboard layout.
    -- Default: "us"

    layout = "us",

    -- Key repeat rate in characters per second.
    -- Default: 25

    repeat_rate = 25,

    -- Delay before key repeat starts in milliseconds.
    -- Default: 600

    repeat_delay = 600,
})

-- --------------------------------------------------------
-- Layout
-- --------------------------------------------------------

feather.layout({
    -- Available options: master
    -- Default: "master"

    mode = "master",
})

feather.layout.master({
    -- Master window size factor.
    -- Default: 0.5 = 50%

    factor = 0.5,
})